# ═══════════════════════════════════════════════════════════════
# RabbitMQ — BASE Configuration
# ═══════════════════════════════════════════════════════════════

# Networking
listeners.tcp.default = 5672
management.tcp.port = 15672

# Security
loopback_users.guest = false

# Memory Management
vm_memory_high_watermark.relative = 0.4

# Disk Management
disk_free_limit.relative = 1.0

# Management UI
management.load_definitions = /etc/rabbitmq/definitions.json

# Prometheus
prometheus.return_per_object_metrics = true
